### ISSUE TITLE
Near future roadmap

### ISSUE THREAD

**Issue by mfeurer** [automl/HPOlib#99]
# HPOlib roadmap for the near future

## Todos for version 0.2

- [ ] Fix an undocumented bug that occurs when HPOlib ends
- [ ] check that the documentation is up to date with the current code

## version 0.3

- [ ] easier optimizer interface
- [ ] redefined benchmark CLI calls
- [ ] automated generation of result tables
